<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Guideline;
use Illuminate\Support\Str;

class GuidelinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $guidelines = [
            [
                'title' => 'Billiards 101: A Complete Beginner\'s Guide',
                'slug' => 'billiards-101-complete-beginners-guide',
                'description' => 'Everything you need to know to start playing billiards like a pro.',
                'content' => '<p>This comprehensive guide covers all the basics of billiards for beginners. From understanding the equipment to learning basic shots, this guide will help you get started on your billiards journey.</p><h3>Equipment Basics</h3><p>First, let\'s understand the basic equipment:</p><ul><li>Cue stick: Your primary tool for hitting the balls</li><li>Cue ball: The white ball you hit with your cue</li><li>Object balls: The numbered balls you aim to pocket</li><li>Table: The playing surface with six pockets</li></ul><p>Choosing the right cue is important. For beginners, a standard 57-inch cue with a medium tip (12-13mm) is recommended.</p><h3>Basic Stance and Grip</h3><p>Your stance should be comfortable and stable. Place your feet shoulder-width apart, with your dominant foot slightly forward. Bend at the waist, not the knees. Your grip should be light but firm, with your hand about 6 inches from the butt of the cue.</p><h3>Basic Shots</h3><p>Start by practicing straight shots. Aim directly at the center of the object ball with the cue ball. As you improve, you can learn more complex shots like draw shots and follow shots.</p><p>Remember, practice makes perfect. Spend time at the table regularly to improve your skills.</p>',
                'skill_level' => 'beginner',
                'category' => 'BEGINNER',
                'tags' => 'billiards, basics, beginner, cue, balls',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example1',
                'is_new' => true,
                'is_featured' => true,
                'views_count' => 120,
                'reading_time_minutes' => 8,
                'author_name' => 'Coach Wilson',
                'published_at' => now(),
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Advanced Aiming Systems: Ghost Ball, Parallel Aiming, and More',
                'slug' => 'advanced-aiming-systems',
                'description' => 'Master the art of precision aiming with these advanced techniques.',
                'content' => '<p>In this guide, we explore different aiming systems used by professional players to improve accuracy and consistency.</p><h3>Ghost Ball Method</h3><p>The ghost ball method involves imagining a "ghost" ball in contact with the object ball, exactly where the cue ball needs to be at impact. Aim your cue at the center of this imaginary ghost ball.</p><h3>Parallel Aiming</h3><p>This system involves aligning your cue parallel to the intended path of the object ball. It\'s particularly useful for shots at sharp angles.</p><h3>Center-to-Edge System</h3><p>This system focuses on the contact point between the cue ball and object ball. Aim from the center of the cue ball to the edge of the object ball where contact should occur.</p><p>Practice these systems regularly to find which works best for your playing style.</p>',
                'skill_level' => 'intermediate',
                'category' => 'INTERMEDIATE',
                'tags' => 'aiming, ghost ball, parallel aiming, intermediate',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example2',
                'is_new' => false,
                'is_featured' => true,
                'views_count' => 85,
                'reading_time_minutes' => 12,
                'author_name' => 'Pro Player Smith',
                'published_at' => now()->subDays(5),
                'status' => 'published',
                'created_at' => now()->subDays(5),
                'updated_at' => now(),
            ],
            [
                'title' => 'Strategic Shot Selection: Thinking Three Moves Ahead',
                'slug' => 'strategic-shot-selection',
                'description' => 'Learn how to plan your shots and think strategically like a master player.',
                'content' => '<p>The difference between good players and great players is strategic thinking. This guide will teach you how to plan multiple shots ahead.</p><h3>Position Play</h3><p>Always consider where the cue ball will end up after your shot. Position it for your next shot by controlling speed and using spin.</p><h3>Safety Plays</h3><p>Sometimes the best strategy is to play defensively. Learn when to play safe by leaving your opponent with difficult shots.</p><h3>Pattern Recognition</h3><p>Master players recognize patterns on the table quickly. Practice identifying the optimal sequence for clearing balls.</p><p>Remember, billiards is as much a mental game as it is physical. Developing your strategic thinking will elevate your game to new heights.</p>',
                'skill_level' => 'master',
                'category' => 'MASTER',
                'tags' => 'strategy, planning, master level, shot selection',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example3',
                'is_new' => true,
                'is_featured' => false,
                'views_count' => 42,
                'reading_time_minutes' => 15,
                'author_name' => 'Champion Johnson',
                'published_at' => now()->subDays(2),
                'status' => 'published',
                'created_at' => now()->subDays(2),
                'updated_at' => now(),
            ],
            [
                'title' => 'The History of Billiards: From Kings to Modern Champions',
                'slug' => 'history-of-billiards',
                'description' => 'Explore the fascinating evolution of billiards through the centuries.',
                'content' => '<p>Billiards has a rich history dating back to the 15th century. This article explores how the game evolved from royal courts to public halls.</p><h3>Royal Beginnings</h3><p>Billiards began as a lawn game similar to croquet, played by European nobility. It moved indoors to tables around the 15th century.</p><h3>Evolution of Equipment</h3><p>Early tables had wooden rails, flat walls, and were covered with cloth. Cues evolved from maces (similar to croquet mallets) when players needed to reach balls near the rail.</p><h3>Modern Era</h3><p>The 20th century saw standardization of rules and equipment, leading to professional competitions and legendary players like Willie Mosconi and Minnesota Fats.</p><p>Understanding billiards\' history gives players appreciation for the game\'s traditions and evolution.</p>',
                'skill_level' => 'general',
                'category' => 'GENERAL',
                'tags' => 'history, evolution, champions, general knowledge',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example4',
                'is_new' => false,
                'is_featured' => true,
                'views_count' => 156,
                'reading_time_minutes' => 10,
                'author_name' => 'Historian Davis',
                'published_at' => now()->subDays(10),
                'status' => 'published',
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            // Tambahan guidelines baru
            [
                'title' => 'Mastering the Break Shot: Power and Precision',
                'slug' => 'mastering-break-shot',
                'description' => 'Learn how to perform the perfect break shot with both power and accuracy.',
                'content' => '<p>The break shot is one of the most important shots in pool. A good break can set you up for success, while a poor break can give your opponent an advantage.</p><h3>Stance and Alignment</h3><p>For maximum power, position your back foot about 45 degrees to the shot line. Your front foot should be pointing toward the cue ball.</p><h3>Grip and Bridge</h3><p>Use a closed bridge for stability and grip the cue a bit farther back than usual for more power. Keep your grip relaxed until the final moment.</p><h3>Cue Ball Placement</h3><p>For 8-ball, place the cue ball slightly off-center to help control where it goes after contact. For 9-ball, aim directly at the head ball.</p><p>Practice your break regularly, focusing on both power and accuracy. A consistent break is a hallmark of a skilled player.</p>',
                'skill_level' => 'intermediate',
                'category' => 'INTERMEDIATE',
                'tags' => 'break shot, power, technique, intermediate',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example5',
                'is_new' => true,
                'is_featured' => true,
                'views_count' => 78,
                'reading_time_minutes' => 9,
                'author_name' => 'Break Master Jones',
                'published_at' => now()->subDays(3),
                'status' => 'published',
                'created_at' => now()->subDays(3),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding English: How to Use Side Spin Effectively',
                'slug' => 'understanding-english-side-spin',
                'description' => 'Master the art of applying English (side spin) to control the cue ball with precision.',
                'content' => '<p>English, or side spin, is one of the most powerful tools in a billiards player\'s arsenal. This guide explains how to use it effectively.</p><h3>What is English?</h3><p>English refers to hitting the cue ball off-center to impart side spin. Right English (hitting right of center) makes the cue ball spin clockwise, while left English makes it spin counter-clockwise.</p><h3>When to Use English</h3><p>Use English to: alter the cue ball\'s path after it hits a rail, adjust the angle the cue ball takes after hitting an object ball, or to minimize throw effects.</p><h3>Common Mistakes</h3><p>Avoid applying too much English, which can cause miscues. Start with subtle English and gradually increase as you gain confidence.</p><p>Remember that English affects both the cue ball\'s path after hitting a rail and the angle it takes after hitting an object ball.</p>',
                'skill_level' => 'intermediate',
                'category' => 'INTERMEDIATE',
                'tags' => 'english, side spin, cue ball control, intermediate',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example6',
                'is_new' => false,
                'is_featured' => true,
                'views_count' => 92,
                'reading_time_minutes' => 11,
                'author_name' => 'Spin Doctor Williams',
                'published_at' => now()->subDays(7),
                'status' => 'published',
                'created_at' => now()->subDays(7),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bank Shots and Kick Shots: Mastering the Rails',
                'slug' => 'bank-shots-kick-shots-mastering-rails',
                'description' => 'Learn advanced techniques for making successful bank shots and kick shots.',
                'content' => '<p>Bank shots (object ball hitting rail) and kick shots (cue ball hitting rail) are essential skills for advanced players. This guide covers the principles and techniques for both.</p><h3>Basic Principles</h3><p>For simple bank shots, the angle of reflection equals the angle of incidence. However, factors like speed, spin, and table conditions can alter this.</p><h3>Diamond System</h3><p>Learn to use the diamonds on the rails as reference points for calculating angles. The diamond system is particularly useful for kick shots.</p><h3>Speed Control</h3><p>The speed at which you hit the ball affects its path after hitting the rail. Slower shots tend to follow the natural angle more closely.</p><p>Practice is crucial for developing a feel for these shots. Start with simple one-rail banks and kicks before attempting more complex multi-rail shots.</p>',
                'skill_level' => 'master',
                'category' => 'MASTER',
                'tags' => 'bank shots, kick shots, rails, diamonds, master level',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example7',
                'is_new' => true,
                'is_featured' => false,
                'views_count' => 64,
                'reading_time_minutes' => 14,
                'author_name' => 'Rail Master Thompson',
                'published_at' => now()->subDays(4),
                'status' => 'published',
                'created_at' => now()->subDays(4),
                'updated_at' => now(),
            ],
            [
                'title' => 'Billiards Etiquette: Unwritten Rules Every Player Should Know',
                'slug' => 'billiards-etiquette-unwritten-rules',
                'description' => 'Learn the proper etiquette and unwritten rules that will make you a respected player at any pool hall.',
                'content' => '<p>Billiards has a rich tradition of etiquette that extends beyond the official rules. Understanding these unwritten rules will help you fit in at any pool hall or tournament.</p><h3>During Your Opponent\'s Turn</h3><p>Stay seated or stand away from the table. Avoid talking, making noise, or moving in your opponent\'s line of sight. Never offer advice unless asked.</p><h3>Table Courtesy</h3><p>Always ask before warming up on someone else\'s table. Avoid leaning on the table or placing drinks on the rails. Use a bridge (mechanical bridge) rather than climbing on the table for difficult shots.</p><h3>After the Game</h3><p>Shake hands regardless of the outcome. If you\'ve been playing on a coin-operated table, offer to split the cost of another game if appropriate.</p><p>Following proper etiquette shows respect for both the game and your fellow players.</p>',
                'skill_level' => 'general',
                'category' => 'GENERAL',
                'tags' => 'etiquette, rules, sportsmanship, general knowledge',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example8',
                'is_new' => false,
                'is_featured' => false,
                'views_count' => 112,
                'reading_time_minutes' => 7,
                'author_name' => 'Etiquette Expert Brown',
                'published_at' => now()->subDays(12),
                'status' => 'published',
                'created_at' => now()->subDays(12),
                'updated_at' => now(),
            ],
            [
                'title' => 'Choosing Your First Cue: A Buyer\'s Guide',
                'slug' => 'choosing-first-cue-buyers-guide',
                'description' => 'Everything beginners need to know about selecting their first personal cue stick.',
                'content' => '<p>Buying your first cue is an important step in your billiards journey. This guide will help you make an informed decision.</p><h3>Cue Weight</h3><p>Most cues range from 18-21 ounces. Beginners often benefit from a medium weight (19oz). Lighter cues offer more control but less power, while heavier cues provide more power but can be harder to control.</p><h3>Shaft Material and Taper</h3><p>Maple is the most common shaft material. Pro taper (gradually narrowing) is versatile for most playing styles. European taper (uniform until near the tip) offers more control for english.</p><h3>Tip Hardness</h3><p>Medium tips are best for beginners. Soft tips hold chalk better and impart more spin but wear faster. Hard tips last longer but offer less spin.</p><h3>Budget Considerations</h3><p>A good starter cue costs between $100-200. Avoid very cheap cues, as they often warp and have poor construction.</p><p>Remember that a well-maintained cue can last for years, so it\'s worth investing in quality from the start.</p>',
                'skill_level' => 'beginner',
                'category' => 'BEGINNER',
                'tags' => 'equipment, cue stick, buying guide, beginner',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example9',
                'is_new' => true,
                'is_featured' => false,
                'views_count' => 145,
                'reading_time_minutes' => 10,
                'author_name' => 'Equipment Specialist Garcia',
                'published_at' => now()->subDays(6),
                'status' => 'published',
                'created_at' => now()->subDays(6),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mental Game in Billiards: Psychological Strategies for Winning',
                'slug' => 'mental-game-billiards-psychological-strategies',
                'description' => 'Discover how top players use mental techniques to stay focused and perform under pressure.',
                'content' => '<p>The mental aspect of billiards is often what separates champions from other skilled players. This guide explores psychological strategies to improve your game.</p><h3>Pre-Shot Routine</h3><p>Develop a consistent pre-shot routine to maintain focus and reduce anxiety. This might include taking a deep breath, visualizing the shot, and approaching the table the same way each time.</p><h3>Handling Pressure</h3><p>Learn to embrace pressure rather than avoid it. Practice pressure situations by setting consequences for missed shots during practice.</p><h3>Dealing with Mistakes</h3><p>Even professionals miss shots. Develop a "next shot" mentality—acknowledge the mistake, learn from it, then let it go and focus on the next opportunity.</p><h3>Visualization</h3><p>Before approaching the table, visualize both the shot and the cue ball\'s path afterward. This mental rehearsal improves execution and position play.</p><p>The mental game requires practice just like physical skills. Dedicate time to developing your mental toughness and focus.</p>',
                'skill_level' => 'master',
                'category' => 'MASTER',
                'tags' => 'mental game, psychology, focus, pressure, master level',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example10',
                'is_new' => false,
                'is_featured' => true,
                'views_count' => 87,
                'reading_time_minutes' => 13,
                'author_name' => 'Mind Coach Anderson',
                'published_at' => now()->subDays(8),
                'status' => 'published',
                'created_at' => now()->subDays(8),
                'updated_at' => now(),
            ],
            [
                'title' => 'Common Billiards Myths Debunked',
                'slug' => 'common-billiards-myths-debunked',
                'description' => 'Separate fact from fiction with this exploration of popular misconceptions about billiards.',
                'content' => '<p>The world of billiards is full of myths and misconceptions. This article examines common beliefs and reveals the truth behind them.</p><h3>Myth: Chalk Before Every Shot</h3><p>Truth: While chalk is important, excessive chalking is unnecessary and can create mess. Chalk after miscues or every few shots is sufficient.</p><h3>Myth: Breaking Hard is Always Best</h3><p>Truth: Control and accuracy in breaking are often more important than raw power. Many top players use moderate power with precise aim.</p><h3>Myth: Expensive Cues Make You Play Better</h3><p>Truth: While quality matters, an expensive cue won\'t automatically improve your game. Proper technique and practice are far more important.</p><h3>Myth: Pool is All Geometry and Physics</h3><p>Truth: While physics principles apply, feel and intuition developed through practice are equally important for high-level play.</p><p>Understanding these truths can help you focus on what really matters for improving your game.</p>',
                'skill_level' => 'general',
                'category' => 'GENERAL',
                'tags' => 'myths, misconceptions, facts, general knowledge',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example11',
                'is_new' => true,
                'is_featured' => false,
                'views_count' => 103,
                'reading_time_minutes' => 8,
                'author_name' => 'Myth Buster Taylor',
                'published_at' => now()->subDays(5),
                'status' => 'published',
                'created_at' => now()->subDays(5),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cue Ball Control: Mastering Stop, Follow, and Draw Shots',
                'slug' => 'cue-ball-control-stop-follow-draw',
                'description' => 'Learn the three fundamental cue ball control techniques that form the basis of position play.',
                'content' => '<p>Controlling the cue ball is essential for playing position for your next shot. This guide covers the three basic control shots every player should master.</p><h3>Stop Shot</h3><p>Hit the cue ball at its center (or slightly below) with medium speed to make it stop upon contact with the object ball. Perfect for when you want the cue ball to remain near the contact point.</p><h3>Follow Shot</h3><p>Hit the cue ball above center to make it follow the object ball after contact. The higher you hit (within reason), the more forward roll the cue ball will have.</p><h3>Draw Shot</h3><p>Hit the cue ball below center to make it draw backward after contact with the object ball. The lower you hit (without miscuing), the more draw you\'ll achieve.</p><h3>Practice Drills</h3><p>Set up a straight shot and practice achieving consistent results with each technique. Gradually increase the distance between balls as you improve.</p><p>Mastering these three shots will dramatically improve your position play and overall game.</p>',
                'skill_level' => 'beginner',
                'category' => 'BEGINNER',
                'tags' => 'cue ball control, stop shot, follow shot, draw shot, beginner',
                'featured_image' => 'guideline-1.png',
                'youtube_url' => 'https://youtube.com/example12',
                'is_new' => false,
                'is_featured' => true,
                'views_count' => 132,
                'reading_time_minutes' => 9,
                'author_name' => 'Control Expert Martinez',
                'published_at' => now()->subDays(9),
                'status' => 'published',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
        ];

        Guideline::insert($guidelines);
    }
}